// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN8mGKUitQTxfYOtYt7G4ZX8mq4ysgvNw',
    appId: '1:164382619834:web:4d8cbf47ec0489149d2a83',
    messagingSenderId: '164382619834',
    projectId: 'saranelapp',
    authDomain: 'saranelapp.firebaseapp.com',
    storageBucket: 'saranelapp.appspot.com',
    measurementId: 'G-5MKQ4FW0YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI93dzsC8Vgk3kos-1xc9KZrP9eGwIcAQ',
    appId: '1:164382619834:android:12721a9ead752b779d2a83',
    messagingSenderId: '164382619834',
    projectId: 'saranelapp',
    storageBucket: 'saranelapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLMEb7N7fLaUDyvdho4AMKQWX_e35_dc',
    appId: '1:164382619834:ios:d6c7107dcc21fc069d2a83',
    messagingSenderId: '164382619834',
    projectId: 'saranelapp',
    storageBucket: 'saranelapp.appspot.com',
    iosClientId: '164382619834-bhorrn9n873g362jl69iaad5vlumg6hl.apps.googleusercontent.com',
    iosBundleId: 'com.saraneltr.saranelApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLMEb7N7fLaUDyvdho4AMKQWX_e35_dc',
    appId: '1:164382619834:ios:37d70b2736e658769d2a83',
    messagingSenderId: '164382619834',
    projectId: 'saranelapp',
    storageBucket: 'saranelapp.appspot.com',
    iosClientId: '164382619834-nc6543c08sbdo02cg3so0qdimqfnupk6.apps.googleusercontent.com',
    iosBundleId: 'com.saraneltr.saranelApplication.RunnerTests',
  );
}
